import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import { FiChevronDown } from "react-icons/fi";
import { CiGlobe } from "react-icons/ci";

export default function Home() {
  const router = useRouter();
  const [inputType, setInputType] = useState("password");
  const handleEnterList = (e) => {
    e.preventDefault();
    router.push("register");
  };

  return (
    <div className="bg-[#F5FAFB]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" w-full  relative h-[100vh] bg-[#E6F0F3] ">
        <div className="w-[1020px] mx-auto relative">
          <span className=" absolute bg-[url('../images/top-left.png')] w-[250px] h-[316px] left-[24px] top-[32px] bg-no-repeat"></span>
          <span className="absolute bg-[url('../images/top-bottom.png')] w-[150px] h-[180px] left-[56px] top-[323px] bg-no-repeat"></span>
          <span className="absolute bg-[url('../images/middle.png')] w-[130px] h-[140px] left-[471px] top-[54px] bg-no-repeat "></span>
          <span className=" absolute  bg-[url('../images/top-right.png')] w-[268px] h-[290px] left-[676px] top-[32px] bg-no-repeat"></span>
        </div>
        <div className=" bg-[url('../images/young-doctor1.png')] w-[1020px] h-[100vh] mx-auto bg-no-repeat  left-0 bottom-0 "></div>
      </div>

      <div className="w-[1020px] v-[100vh] mx-auto relative  flex flex-col justify-center items-center">
        <div className="border relative flex items-center justify-center border-[#C5D7D8] rounded-full bg-white w-[123px] h-[123px] mt-[50px] ">
          <span className="bg-[url('../images/Frame.png')] bg-contain w-[90px] h-[85px] bg-no-repeat absolute"></span>
        </div>
        <div className="flex flex-col items-center w-[397px]  ">
          <h2 className="text-[24px] text-center w-[213px] text-[Black] mx-auto font-[500] leading-[38px]">
            Tizmga <span className="text-[#1BB7B5]">kirish</span>
          </h2>
          <form
            action=""
            className="w-full flex flex-col "
            autoComplete="off"
            method="POST"
          >
            <label htmlFor="login" className="mt-[10px] mb-2 text-[#759495]">
              Login (Passport seriya)
            </label>
            <input
              name="login"
              className="border border-[#D7E6E7] rounded-[12px] p-2"
              type="text"
              placeholder="Loginni kiriting"
              autoComplete="off"
            />
            <label
              htmlFor="password"
              className="mt-[14px]  mb-2 text-[#759495]"
            >
              Parol
            </label>
            <div className="border relative border-[#D7E6E7] rounded-[12px]">
              <input
                name="password"
                className=" w-full p-2 rounded-[12px]"
                type={inputType}
                placeholder="*******"
                autoComplete="off"
              />
              <span
                onClick={() => {
                  inputType === "password"
                    ? setInputType("text")
                    : setInputType("password");
                }}
                className="bg-[url('../images/glass.png')] w-[22px] bg-no-repeat h-[14px] absolute right-4 top-3"
              ></span>
            </div>
            <button className="mt-[24px] py-[13px] bg-gradient-to-t from-[#1BB7B5] to-[#0EC5C9] text-white rounded-[12px]  font-[500] hover:bg-gradient-to-t hover:from-[#0F9694] hover:to-[#0A7476]">
              Kirish
            </button>
            <button
              className="py-[13px] mt-[12px] bg-white text-[#1BB7B5] font-[500] rounded-[12px]
            hover:bg-gradient-to-t hover:from-[#1BB7B5] hover:to-[#12A7AA] hover:text-white"
              onClick={handleEnterList}
            >
              Ro&apos;yhatdan o&apos;tish
            </button>
          </form>
        </div>
        <div className="flex w-[111px] h-[44px] items-center justify-between border border-[#D7E6E7]  rounded-[12px] px-[13px] py-[10px] mt-[62px]  ml-[850px]">
          <CiGlobe className="text-[#1BB7B5] text-xl" />
          <select
            name=""
            id=""
            style={{ WebkitAppearance: "none" }}
            className="outline-none  bg-[#F5FAFB] px-2 absolute ml-7 pr-10  bg-transparent font-[500] "
          >
            <option value="uz">UZ</option>
            <option value="ru">RU</option>
          </select>
          <FiChevronDown className="text-xl" />
        </div>
      </div>
    </div>
  );
}
